baseURL = 'https://roeegg2.github.io/'
languageCode = 'en-us'
title = "Roeegg2's Blog"
theme = 'dusk'

[[menu.main]]
    url = "/posts"
    name = "Single Posts"
    weight = 1

[[menu.main]]
    url = "/series"
    name = "Series"
    weight = 2

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 4

[params]
	theme_colors = "default-dark"
	
[taxonomies]
	series = "series"
