baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'diary'

[[menu.main]]
    url = "/posts"
    name = "Single Posts"
    weight = 1

[[menu.main]]
    url = "/series"
    name = "Series"
    weight = 2

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 4
