baseURL = 'https://roeegg2.github.io/'
languageCode = 'en-us'
title = "Roeegg2's Blog"
theme = 'dusk'

[[menu.main]]
    weight = 3
    name = "Tags"
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    weight = 4
    name = "About"
    url = "/about"
    identifier = "about"

[params]
	theme_colors = "default-dark"
	
[taxonomies]
	tags = "tags"
